Repository openshift/sig-storage-local-static-provisioner, pull requests merged in 2019-06, with the labels that each got.

#2 Add openshift config
  Dockerfile.openshift
  Dockerfile.rhel7
  OWNERS
  OWNERS_ALIASES
Labels: size/M

#7 add myself to maintainers
  OWNERS_ALIASES
Labels: approved, lgtm, needs-ok-to-test, size/XS

#4 Update master branch
  docs/getting-started.md
  hack/release.sh
Labels: approved, lgtm, size/S

#9 Add file system utils
  Dockerfile.openshift
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS
